# Generated by Django 4.0.2 on 2022-03-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='course_old',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='fullname_user',
            new_name='full_name_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
