# Generated by Django 4.0.2 on 2022-03-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_course_old_task_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='full_name_user',
            new_name='fullname_user',
        ),
    ]
