# Generated by Django 4.0.2 on 2022-03-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='choice',
            field=models.CharField(blank=True, choices=[('1', 'Yes, I can'), ('2', 'No, I can not'), ('3', 'I want to learn to play')], max_length=30, null=True, verbose_name='Can you play dombyra'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Your other skills and some facts'),
        ),
    ]
