# Generated by Django 4.0.2 on 2022-03-24 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0005_task_choice_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fullname_user',
            field=models.CharField(max_length=500, verbose_name='Name and Surname'),
        ),
        migrations.AlterField(
            model_name='task',
            name='year_old',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.CreateModel(
            name='Task_music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_user', models.CharField(max_length=500, verbose_name='Name and Surname')),
                ('year_old', models.IntegerField(verbose_name='Age')),
                ('course', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('choice', models.CharField(blank=True, choices=[('1', 'Yes, I can'), ('2', 'No, I can not'), ('3', ' I can play instruments')], max_length=30, null=True, verbose_name='Can you sing songs ? ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Your other skills and some facts')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
