# Generated by Django 4.0.3 on 2022-03-26 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_user', models.CharField(max_length=500, verbose_name='Name and Surname')),
                ('year_old', models.PositiveIntegerField(verbose_name='Age')),
                ('course', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('art', models.CharField(blank=True, choices=[('1', 'Yes, I can'), ('2', 'No, I can not'), ('3', ' I want to  learn')], max_length=30, null=True, verbose_name='Can you draw ? ')),
                ('image', models.ImageField(upload_to='blog', verbose_name='Your works')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Your other skills and some facts')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='task_music',
            name='choice',
        ),
        migrations.AddField(
            model_name='task',
            name='select_kyu',
            field=models.CharField(choices=[('1', 'Ерке Сылқым'), ('2', 'Адай'), ('3', 'Сарыарқа'), ('4', 'Балбырауын')], default='1', max_length=30, verbose_name='Select your known kyu'),
        ),
        migrations.AddField(
            model_name='task_music',
            name='instrument',
            field=models.CharField(default='guitar', max_length=50, verbose_name='If you play an instrument,which one?'),
        ),
        migrations.AddField(
            model_name='task_music',
            name='music',
            field=models.CharField(blank=True, choices=[('1', 'Yes, I can'), ('2', 'No, I can not'), ('3', ' I can play an instrument')], max_length=30, null=True, verbose_name='Can you sing songs ? '),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='year_old',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='task_music',
            name='course',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='task_music',
            name='year_old',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
    ]
