# Generated by Django 4.0.3 on 2022-03-27 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0008_task_art_delete_customer_remove_task_music_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_user', models.CharField(max_length=500, verbose_name='Name and Surname')),
                ('year_old', models.PositiveIntegerField(verbose_name='Age')),
                ('course', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('vison', models.CharField(blank=True, choices=[('1', 'Yes, I can'), ('2', 'No, I can not')], max_length=30, null=True, verbose_name='Have you ever been a volunteer for a charity ? ')),
                ('cause', models.CharField(max_length=2000, verbose_name='If yes,then what was it like?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Your other skills and some facts')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
