# Generated by Django 4.0.3 on 2022-03-27 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0009_task_vision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_vision',
            old_name='vison',
            new_name='vision',
        ),
        migrations.CreateModel(
            name='Task_debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname_user', models.CharField(max_length=500, verbose_name='Name and Surname')),
                ('year_old', models.PositiveIntegerField(verbose_name='Age')),
                ('course', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('debate', models.CharField(blank=True, choices=[('1', 'Kazakh'), ('2', 'Russian'), ('3', 'Turkish')], max_length=30, null=True, verbose_name='Please,select language that for you comfortable')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Your other skills and some facts')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
