# Generated by Django 4.0.2 on 2022-03-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_rename_vison_task_vision_vision_task_debate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, upload_to='post_image')),
            ],
        ),
    ]
