# Generated by Django 4.0.2 on 2022-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='head',
            name='image',
        ),
    ]
