# Generated by Django 4.0.3 on 2022-05-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_blogmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task_art',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task_debate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task_music',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task_vision',
            name='user',
        ),
    ]
