# Generated by Django 4.0.3 on 2022-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_remove_task_user_remove_task_art_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=200, verbose_name='Name')),
                ('order_phone', models.CharField(max_length=200, verbose_name='Phone')),
            ],
        ),
    ]
