# Generated by Django 4.0.2 on 2022-05-18 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='body',
            field=models.TextField(default='DebateClub'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(default='DebateClub', max_length=255),
        ),
    ]
