# Generated by Django 4.0.2 on 2022-05-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_alter_blogmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
