# Generated by Django 4.0.2 on 2022-05-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='body',
        ),
    ]
